### ISSUE TITLE
Can't embedd two bandcamp iframes

### ISSUE THREAD

**Issue by caprenter** [notshi/mainhobby#10]
@notshi - No idea why but the bandcamp embed seems to be showing the smae album twice, but the album id is different.

code from bandcamp is 

`<iframe style="border: 0; width: 350px; height: 470px;" src="https://bandcamp.com/EmbeddedPlayer/album=2792388851/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=false/transparent=true/" seamless><a href="https://mainhobby.bandcamp.com/album/good-enough">Good Enough by Main Hobby</a></iframe>`

**Comment by caprenter** [comment]
although ctrl+shift+r seems to have fixed it maybe...

**Comment by notshi** [comment]
sounds like a cache issue - working fine on both desktop and mobile here :)

**Comment by caprenter** [comment]
yup
